### ISSUE TITLE
error  no mapnik-jni in java.library.path

### ISSUE THREAD

**Issue by lzp0070007** [pmauduit/mapnik-java#1]
why  this error in console  ,please!!!

```
java.lang.UnsatisfiedLinkError: no mapnik-jni in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[na:1.8.0_191]
	at java.lang.Runtime.loadLibrary0(Unknown Source) ~[na:1.8.0_191]
	at java.lang.System.loadLibrary(Unknown Source) ~[na:1.8.0_191]
	at mapnik.Mapnik.initialize(Mapnik.java:91) ~[mapnik-jni.jar:na]
	at mapnik.Mapnik.initialize(Mapnik.java:127) ~[mapnik-jni.jar:na]
```

**Comment by pmauduit** [comment]
you will probably need to install libmapnik, under debian sid the package is named `libmapnik3.0`. To be honest, I cannot exactly remember what was the purpose of this repository ... :-)

**Comment by lzp0070007** [comment]
thanks a  lot!  I want  mvt +mapbox style to  png  use mapnik in java,so I feel this code is very userful，my english is not good！sorry

**Comment by pmauduit** [comment]
by the way, I'm glad if it can help !
